# Generated by Django 4.2.6 on 2023-10-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_alter_studentdetails_admin_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sub2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sub3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sub4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sub5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentdetails')),
            ],
            options={
                'db_table': 'MarkList',
            },
        ),
    ]
