# Generated by Django 4.2.6 on 2023-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marklist',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
