# Generated by Django 4.2.6 on 2023-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=3)),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'StudentDetails',
            },
        ),
    ]
