# Generated by Django 4.2.6 on 2023-10-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='admin_no',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
    ]
